### ISSUE TITLE
 webpack building prints tons of unexpectedly found "\n ... when pnpm host builds webpack

### ISSUE THREAD

**Issue by vimalaad** [cardstack/boxel#1258]
_pnpm host build_ prints tons of _unexpectedly found "\n ..._ on webpack building
![image](https://github.com/cardstack/boxel/assets/4591436/cf789cb2-b6b4-42a1-9ab0-609d141cf21d)

**Comment by backspace** [comment]
Hey, this is a [known issue](https://github.com/emberjs/ember.js/issues/19392) that we are tracking internally, but thanks for filing a report!
