### ISSUE TITLE
Handle orphan interactivity

### ISSUE THREAD

**Issue by nickschot** [cardstack/boxel#25]
Currently orphan elements are interactive which can have weird side effects like causing a full refresh if the orphan contains a link (as it isn't handled by Ember anymore).

A possible nice solution could be to make the orphan attachment div inert through https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/inert (with a polyfill at the moment).

**Comment by Aierie** [comment]
Inert is coming to Chrome 102, on by default!

**Comment by lukemelia** [comment]
Closing as unfnished in anticipation of alpha release.
