### ISSUE TITLE
Composite style handling (color, transform etc.)

### ISSUE THREAD

**Issue by nickschot** [cardstack/boxel#27]
In most cases it is preferable to have the default `replace` behaviour that we have currently for (web) animations (i.e. "I want to animate from opacity 0 to 1 regardless of what the current value is").

One special case that I ran into is where an element already has a transform defined. We currently provide no nice way to keep that transform in effect, while the user is at the moment simply saying to the system "I want to animate the position of the element".

We probably have to read out the current value and possibly combine it into the keyframes (?) (or automatically select a different composite option in case we detect a pre-existing value that we need to keep).

I'll make a branch with a demo that showcases the issue soon.

**Comment by lukemelia** [comment]
Closing as unfnished in anticipation of alpha release.
