### ISSUE TITLE
Optimize getAnimations() calls

### ISSUE THREAD

**Issue by nickschot** [cardstack/boxel#28]
Two points we need to consider:

1. Using `document.getAnimations()` to pause all animations in willTransition may be more efficient than doing it per sprite as we'd issue a single call to the DOM
2. `getAnimations()` returns all animations, including CSS transitions/animations. Not sure yet if we can distinguish between them and if it matters.

**Comment by nickschot** [comment]
(1) has been implemented in #31 in a very basic way

**Comment by nickschot** [comment]
This may not be needed if we time our DOM reads/writes properly.

**Comment by lukemelia** [comment]
Closing as unfnished in anticipation of alpha release.
