### ISSUE TITLE
Web animation pausing/cancellation quirks

### ISSUE THREAD

**Issue by nickschot** [cardstack/boxel#29]
From benchmarking a little with a hundred instances of the interruption demo (in a single AnimationContext), I've noticed the browser may take quite a while to actually pause or cancel an animation. This can make interruption jarring if the browser is busy as the starting point may not match the measuring point anymore.

Not explicitly cancelling animations as well as pausing animations before any other work (through `document.getAnimations()` rather than per sprite) seems to mostly fix this.

Need to investigate further.

**Comment by nickschot** [comment]
Part of the issue appears to be that pausing/playing animations is scheduled on the task queue and as such is mostly useless for our purposes as we synchronously want to measure.

Details: https://drafts.csswg.org/web-animations-1/#pausing-an-animation-section

**Comment by lukemelia** [comment]
Closing as unfnished in anticipation of alpha release.
