### ISSUE TITLE
Running the realm-server fails with Fastboot TypeError 

### ISSUE THREAD

**Issue by vimalaad** [cardstack/boxel#731]
After pulling the latest GitHub source now the `pnpm start:all` inside /realm-server fails with the following  error:
"There was an error running your app in fastboot. More info about the error: 
 TypeError: (0 , _cardstack_runtime_common_code_ref__WEBPACK_IMPORTED_MODULE_8__.isBaseDef) is not a function"

**Comment by backspace** [comment]
Did you start/build the `host` application first?

**Comment by vimalaad** [comment]
> Did you start/build the `host` application first?
Yes

**Comment by vimalaad** [comment]
A clean installation works for me.
